### ISSUE TITLE
Bad response from server: (0 [error,getplugins]) 

### ISSUE THREAD

**Issue by Koldnitz** [romancin/rutorrent-docker#1]
I was using rutorrent-flood, and when you last upgraded the dockerfile to use alpine 3.7, I started getting the error in the title.  I switched over to rutorrent-docker(no flood and older version of dockerfile) and everything worked great.  I just upgraded to latest rutorrent-docker (uses alpine 3.7, new dockerfile) and now I am getting the same error again.   I have tried fixing it by using coxley's method detailed in this link https://github.com/Novik/ruTorrent/issues/974, but that does not work.  I have tried hosing everything in directory and building totally fresh version (totally clean install.  no configs, no session data, no anything and I get the same error).  I am sort of at my wits end, please advise if there is anything else you can think of going on.  If you need any files or more information please let me know I really love your rutorrent docker and really want to get the new versions to work.

**Comment by romancin** [comment]
Hi! Are you using Safari on a Mac? If so, I have the same problem. I have found a workaround, if you delete file manager plugin, it will start working, you can do it executing:

docker exec -it your_rutorrent_container_name rm -rf /var/www/localhost/rutorrent/plugins/filemanager

It stopped working a few months ago, in a php7 update, and I cannot find a way to fix it. Filemanager plugin doesn't update since a lot of time :(
For the moment you have this to options, delete file manager or use Google Chrome, I opted for the second one. Can't live with this plugin.
Try it and tell me how it goes.

**Comment by Koldnitz** [comment]
I am actually on firefox.  Everything was great until you updated rutorrent-flood around december 20th.  After that I switched over to rutorrent, because it was older image and it worked fine.  After today's update everything stopped working.  I will try with chrome, but i already tried with microsoft edge and I had same error

**Comment by romancin** [comment]
Try to delete filemanager plugin please, and tell me how it goes.

I had a bad experience recently with a php application on a public webserver (it was hacked) and I will update images frequently in order to have latest patches.

**Comment by Koldnitz** [comment]
Ok I just installed chrome and it is working fine with latest version of rutorrent docker :)  Thanks a lot for the help.  This if off topic but I was trying to make and image from an earlier build of yours (the update prior to today's update) and I keep getting an error while building image, would you be ok with me asking you questions about this stuff?  I like this docker program and your work especially but I am beginner / intermediate at stuff like this.  Thanks again for help and please let me know if i could ask you more questions / where the best place to do it would be.

**Comment by romancin** [comment]
Yes, you can ask me what you want, no problem.
If the problem is present in all other web browsers but Chrome it is starting to worry me.

I have the problem identified by package versions of the alpine linux, it is not related with the Dockerfile itself. 

You can talk to me by Telegram, my nick is @Romancin.

**Comment by romancin** [comment]
Fixed. Thank you for your help.
